### ISSUE TITLE
Inconsistend display of downtimes in thruk (2.44.3) with lmd+icinga2

### ISSUE THREAD

**Issue by yoshi314** [sni/lmd#114]
Whenever i apply a downtime on multiple services, the effect is not being displayed immediately on the list. 

Even after 20 minutes i see maybe 50%  of services with downtime. Disabling lmd restores normal visibility. I tested this when using lmd with icinga2 ha cluster (2 peers in lmd), and with single instance.

Inspecting individual services via thruk displays their downtimes correctly.

**Comment by sni** [comment]
the problem here is that lmd just passes the commands on to the connected backends but does not understand them. After
sending commands, it triggers an immediate update, but thats worthless, because Icinga2 does not support synchronization
by the last_update column.
I will think about it, maybe lmd needs to run a full table check after sending the commands for Icinga2 backends.

**Comment by sni** [comment]
should be better now
